apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django-app
spec:
  replicas: 1  # Adjust as needed for scaling
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-container
          image: tamilwebappacr.azurecr.io/ven-pkumar-tf/django-web-page:latest  # Ensure this matches your registry
          ports:
            - containerPort: 8000  # Django default port
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "tamil_class_web_page.settings"  # Adjust based on project settings
          volumeMounts:
            - name: static-volume
              mountPath: /app/static  # Mount for static files
      volumes:
        - name: static-volume
          emptyDir: {}  # Temporary volume; replace with persistent storage if needed
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000  # Expose container port externally
  type: LoadBalancer  # Change to ClusterIP if not exposing externally
