apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django-app
spec:
  replicas: 1  # Adjust based on your needs for scaling
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
     containers:
      - name: django-container
        image: tamilwebappacr.azurecr.io/ven-pkumar-tf/django-web-page:latest
        ports:
          - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 8000      # The port exposed by the service
      targetPort: 8000  # The port the container listens on
  type: LoadBalancer   # Expose service externally (requires cloud provider or use NodePort for local setups)

