apiVersion: apps/v1
kind: Deployment
metadata:
  name: tamil-web-app-deploy
  labels:
    app: django-app
spec:
  replicas: 2  # Adjust for scaling
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-container
          image: tamilwebappacr.azurecr.io/ven-pkumar-tf/django-web-page:latest
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "tamil_class_web_page.settings"
            - name: DATABASE_URL
              value: "postgres://user:password@database-host:5432/dbname"
          volumeMounts:
            - name: static-volume
              mountPath: /app/static
      volumes:
        - name: static-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer  # Change to ClusterIP if needed
