trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: project_build
    displayName: "Django Project Build"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true
          architecture: 'x64'

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Install Dependencies from requirements.txt'
      
      - script: |
          python manage.py collectstatic --noinput
          python manage.py migrate
        displayName: 'Run Migrations and Collect Static Files'
      
      # Create a .zip package of the project
      - script: |
          zip -r django_project.zip .  # Create a zip of the project files
        displayName: 'Create .zip File for Deployment'
      
      # Deploy to Azure Web App
      - task: AzureRmWebAppDeployment@5
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'aks-service-connection'  # Replace with your service connection name
          appType: 'webAppLinux'
          WebAppName: 'tamil-web-page-service'  # Replace with your Azure Web App name
          packageForLinux: '$(System.DefaultWorkingDirectory)/django_project.zip'  # Path to the .zip file
          RuntimeStack: 'PYTHON:3.9'  # Ensure this matches the Python version for your app
          DeploymentTypeLinux: 'oneDeploy'
