trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: project_build
    displayName: "Django Project Build"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true
          architecture: 'x64'

      - script: |
          python -m venv Main_Project/venv
          source Main_Project/venv/bin/activate
          pip install --upgrade pip
          pip install -r Main_Project/requirements.txt
        displayName: 'Install Dependencies from requirements.txt'
 
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)/Main_Project'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/django_app.zip'
          replaceExistingArchive: true
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/django_app.zip'
          ArtifactName: 'drop'
          publishLocation: 'Container'
    
  - job: deploy
    displayName: "Deploy to web app service"
    dependsOn: project_build
    steps:
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.ArtifactsDirectory)'
      
      - task: AzureRmWebAppDeployment@5
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'aks-service-connection'
          appType: 'webAppLinux'
          WebAppName: 'tamil-web-page-service'
          packageForLinux: '/home/vsts/work/1/a/drop/django_app.zip'
          RuntimeStack: 'PYTHON:3.12'
          StartupCommand: 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
          DeploymentTypeLinux: 'oneDeploy'
