trigger:
  - main  # Trigger the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

jobs:
  - job: Build
    displayName: 'Build Python App'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.12'
          addToPath: true

      - script: |
          cd tamil_web_page
          python -m venv venv
          source venv/bin/activate
        displayName: 'Create and activate virtual environment'

      - script: |
          cd tamil_web_page
          pip install -r requirements.txt
        displayName: 'Install dependencies'

      - script: |
          zip release.zip ./* -r -x "venv/*"
        displayName: 'Zip artifact for deployment'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'release.zip'
          ArtifactName: 'python-app'
          publishLocation: 'Container'

  - job: Deploy
    displayName: 'Deploy to Azure Web App'
    dependsOn: Build
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          artifactName: 'python-app'
          downloadPath: '$(Build.ArtifactStagingDirectory)'


      - task: AzureWebApp@1
        displayName: 'Deploy to Azure Web App'
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'aks-service-connection'  # Replace with your Azure service connection
          appType: 'webAppLinux'
          WebAppName: 'tamil-web-page-service'  # Replace with your Azure Web App name
          packageForLinux: '/home/vsts/work/1/a/python-app/release.zip'
          RuntimeStack: 'PYTHON|3.12'  # Ensure the correct runtime stack is set for your app
          
