# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: aks_deploy
    displayName: "AKS Deploy"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true
          architecture: 'x64'
      - task: Docker@2
        inputs:
          containerRegistry: 'aks-cluster-server'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: 'latest'
      