# Use an official Python runtime as a parent image
FROM python:3.12

# Set the working directory in the container
WORKDIR /app

# Copy project files into the container
COPY ./tamil_web_page /app

# Install dependencies
RUN python -m venv venv && \
    . venv/bin/activate && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

# Collect static files
RUN . venv/bin/activate && python manage.py collectstatic --noinput

# Expose port 8000
EXPOSE 8000

# Define the command to run the app
CMD ["/app/venv/bin/gunicorn", "--bind", "0.0.0.0:8000", "tamil_web_page.wsgi:application"]
