# Generated by Django 5.0.13 on 2025-03-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
