name: Deploy Django App to Azure Web App

on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: "Azure Login"
        run: |
          az login --service-principal --username "679bf607-d0e5-4ed2-8d84-6d2092e6d944" --password "xK18Q~vSZ9r7y0AxqzC8j0_LTaXKISnj3vvX3cI8" --tenant "f9495402-3d3a-4324-81d6-47a9fe28909c"
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Adjust based on your Django project

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migrations
        run: |
          python manage.py migrate

      - name: Collect Static Files
        run: |
          python manage.py collectstatic --noinput

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "tamil-web-page-service"  # Replace with your Azure Web App name
          package: .
